//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Client.FileTransmute {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileTransmute.FileHandlerSoap")]
    public interface FileHandlerSoap {
        
        // CODEGEN: Generating message contract since element name fileByteStream from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RunTD4C", ReplyAction="*")]
        Web_Client.FileTransmute.RunTD4CResponse RunTD4C(Web_Client.FileTransmute.RunTD4CRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RunTD4C", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Client.FileTransmute.RunTD4CResponse> RunTD4CAsync(Web_Client.FileTransmute.RunTD4CRequest request);
        
        // CODEGEN: Generating message contract since element name fileByteStream from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RunKarmaLego", ReplyAction="*")]
        Web_Client.FileTransmute.RunKarmaLegoResponse RunKarmaLego(Web_Client.FileTransmute.RunKarmaLegoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RunKarmaLego", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Client.FileTransmute.RunKarmaLegoResponse> RunKarmaLegoAsync(Web_Client.FileTransmute.RunKarmaLegoRequest request);
        
        // CODEGEN: Generating message contract since element name fileName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFile", ReplyAction="*")]
        Web_Client.FileTransmute.GetFileResponse GetFile(Web_Client.FileTransmute.GetFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFile", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Client.FileTransmute.GetFileResponse> GetFileAsync(Web_Client.FileTransmute.GetFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunTD4CRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RunTD4C", Namespace="http://tempuri.org/", Order=0)]
        public Web_Client.FileTransmute.RunTD4CRequestBody Body;
        
        public RunTD4CRequest() {
        }
        
        public RunTD4CRequest(Web_Client.FileTransmute.RunTD4CRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RunTD4CRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] fileByteStream;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string documentName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string emailAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string downloadURL;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Web_Client.FileTransmute.ArrayOfString abstractionMethod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string classSeperator;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int binsNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool abstractedSeries;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string datasetName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public byte[] vmap;
        
        public RunTD4CRequestBody() {
        }
        
        public RunTD4CRequestBody(byte[] fileByteStream, string documentName, string emailAddress, string downloadURL, Web_Client.FileTransmute.ArrayOfString abstractionMethod, string classSeperator, int binsNumber, bool abstractedSeries, string datasetName, byte[] vmap) {
            this.fileByteStream = fileByteStream;
            this.documentName = documentName;
            this.emailAddress = emailAddress;
            this.downloadURL = downloadURL;
            this.abstractionMethod = abstractionMethod;
            this.classSeperator = classSeperator;
            this.binsNumber = binsNumber;
            this.abstractedSeries = abstractedSeries;
            this.datasetName = datasetName;
            this.vmap = vmap;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunTD4CResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RunTD4CResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Client.FileTransmute.RunTD4CResponseBody Body;
        
        public RunTD4CResponse() {
        }
        
        public RunTD4CResponse(Web_Client.FileTransmute.RunTD4CResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RunTD4CResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RunTD4CResult;
        
        public RunTD4CResponseBody() {
        }
        
        public RunTD4CResponseBody(string RunTD4CResult) {
            this.RunTD4CResult = RunTD4CResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunKarmaLegoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RunKarmaLego", Namespace="http://tempuri.org/", Order=0)]
        public Web_Client.FileTransmute.RunKarmaLegoRequestBody Body;
        
        public RunKarmaLegoRequest() {
        }
        
        public RunKarmaLegoRequest(Web_Client.FileTransmute.RunKarmaLegoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RunKarmaLegoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] fileByteStream;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string documentName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string emailAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string downloadURL;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int minVerSup;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int maxGap;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int epsilon;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool useHS;
        
        public RunKarmaLegoRequestBody() {
        }
        
        public RunKarmaLegoRequestBody(byte[] fileByteStream, string documentName, string emailAddress, string downloadURL, int minVerSup, int maxGap, int epsilon, bool useHS) {
            this.fileByteStream = fileByteStream;
            this.documentName = documentName;
            this.emailAddress = emailAddress;
            this.downloadURL = downloadURL;
            this.minVerSup = minVerSup;
            this.maxGap = maxGap;
            this.epsilon = epsilon;
            this.useHS = useHS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunKarmaLegoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RunKarmaLegoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Client.FileTransmute.RunKarmaLegoResponseBody Body;
        
        public RunKarmaLegoResponse() {
        }
        
        public RunKarmaLegoResponse(Web_Client.FileTransmute.RunKarmaLegoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RunKarmaLegoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RunKarmaLegoResult;
        
        public RunKarmaLegoResponseBody() {
        }
        
        public RunKarmaLegoResponseBody(string RunKarmaLegoResult) {
            this.RunKarmaLegoResult = RunKarmaLegoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFile", Namespace="http://tempuri.org/", Order=0)]
        public Web_Client.FileTransmute.GetFileRequestBody Body;
        
        public GetFileRequest() {
        }
        
        public GetFileRequest(Web_Client.FileTransmute.GetFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileName;
        
        public GetFileRequestBody() {
        }
        
        public GetFileRequestBody(string fileName) {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Client.FileTransmute.GetFileResponseBody Body;
        
        public GetFileResponse() {
        }
        
        public GetFileResponse(Web_Client.FileTransmute.GetFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetFileResult;
        
        public GetFileResponseBody() {
        }
        
        public GetFileResponseBody(byte[] GetFileResult) {
            this.GetFileResult = GetFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FileHandlerSoapChannel : Web_Client.FileTransmute.FileHandlerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileHandlerSoapClient : System.ServiceModel.ClientBase<Web_Client.FileTransmute.FileHandlerSoap>, Web_Client.FileTransmute.FileHandlerSoap {
        
        public FileHandlerSoapClient() {
        }
        
        public FileHandlerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileHandlerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileHandlerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileHandlerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Client.FileTransmute.RunTD4CResponse Web_Client.FileTransmute.FileHandlerSoap.RunTD4C(Web_Client.FileTransmute.RunTD4CRequest request) {
            return base.Channel.RunTD4C(request);
        }
        
        public string RunTD4C(byte[] fileByteStream, string documentName, string emailAddress, string downloadURL, Web_Client.FileTransmute.ArrayOfString abstractionMethod, string classSeperator, int binsNumber, bool abstractedSeries, string datasetName, byte[] vmap) {
            Web_Client.FileTransmute.RunTD4CRequest inValue = new Web_Client.FileTransmute.RunTD4CRequest();
            inValue.Body = new Web_Client.FileTransmute.RunTD4CRequestBody();
            inValue.Body.fileByteStream = fileByteStream;
            inValue.Body.documentName = documentName;
            inValue.Body.emailAddress = emailAddress;
            inValue.Body.downloadURL = downloadURL;
            inValue.Body.abstractionMethod = abstractionMethod;
            inValue.Body.classSeperator = classSeperator;
            inValue.Body.binsNumber = binsNumber;
            inValue.Body.abstractedSeries = abstractedSeries;
            inValue.Body.datasetName = datasetName;
            inValue.Body.vmap = vmap;
            Web_Client.FileTransmute.RunTD4CResponse retVal = ((Web_Client.FileTransmute.FileHandlerSoap)(this)).RunTD4C(inValue);
            return retVal.Body.RunTD4CResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Client.FileTransmute.RunTD4CResponse> Web_Client.FileTransmute.FileHandlerSoap.RunTD4CAsync(Web_Client.FileTransmute.RunTD4CRequest request) {
            return base.Channel.RunTD4CAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Client.FileTransmute.RunTD4CResponse> RunTD4CAsync(byte[] fileByteStream, string documentName, string emailAddress, string downloadURL, Web_Client.FileTransmute.ArrayOfString abstractionMethod, string classSeperator, int binsNumber, bool abstractedSeries, string datasetName, byte[] vmap) {
            Web_Client.FileTransmute.RunTD4CRequest inValue = new Web_Client.FileTransmute.RunTD4CRequest();
            inValue.Body = new Web_Client.FileTransmute.RunTD4CRequestBody();
            inValue.Body.fileByteStream = fileByteStream;
            inValue.Body.documentName = documentName;
            inValue.Body.emailAddress = emailAddress;
            inValue.Body.downloadURL = downloadURL;
            inValue.Body.abstractionMethod = abstractionMethod;
            inValue.Body.classSeperator = classSeperator;
            inValue.Body.binsNumber = binsNumber;
            inValue.Body.abstractedSeries = abstractedSeries;
            inValue.Body.datasetName = datasetName;
            inValue.Body.vmap = vmap;
            return ((Web_Client.FileTransmute.FileHandlerSoap)(this)).RunTD4CAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Client.FileTransmute.RunKarmaLegoResponse Web_Client.FileTransmute.FileHandlerSoap.RunKarmaLego(Web_Client.FileTransmute.RunKarmaLegoRequest request) {
            return base.Channel.RunKarmaLego(request);
        }
        
        public string RunKarmaLego(byte[] fileByteStream, string documentName, string emailAddress, string downloadURL, int minVerSup, int maxGap, int epsilon, bool useHS) {
            Web_Client.FileTransmute.RunKarmaLegoRequest inValue = new Web_Client.FileTransmute.RunKarmaLegoRequest();
            inValue.Body = new Web_Client.FileTransmute.RunKarmaLegoRequestBody();
            inValue.Body.fileByteStream = fileByteStream;
            inValue.Body.documentName = documentName;
            inValue.Body.emailAddress = emailAddress;
            inValue.Body.downloadURL = downloadURL;
            inValue.Body.minVerSup = minVerSup;
            inValue.Body.maxGap = maxGap;
            inValue.Body.epsilon = epsilon;
            inValue.Body.useHS = useHS;
            Web_Client.FileTransmute.RunKarmaLegoResponse retVal = ((Web_Client.FileTransmute.FileHandlerSoap)(this)).RunKarmaLego(inValue);
            return retVal.Body.RunKarmaLegoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Client.FileTransmute.RunKarmaLegoResponse> Web_Client.FileTransmute.FileHandlerSoap.RunKarmaLegoAsync(Web_Client.FileTransmute.RunKarmaLegoRequest request) {
            return base.Channel.RunKarmaLegoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Client.FileTransmute.RunKarmaLegoResponse> RunKarmaLegoAsync(byte[] fileByteStream, string documentName, string emailAddress, string downloadURL, int minVerSup, int maxGap, int epsilon, bool useHS) {
            Web_Client.FileTransmute.RunKarmaLegoRequest inValue = new Web_Client.FileTransmute.RunKarmaLegoRequest();
            inValue.Body = new Web_Client.FileTransmute.RunKarmaLegoRequestBody();
            inValue.Body.fileByteStream = fileByteStream;
            inValue.Body.documentName = documentName;
            inValue.Body.emailAddress = emailAddress;
            inValue.Body.downloadURL = downloadURL;
            inValue.Body.minVerSup = minVerSup;
            inValue.Body.maxGap = maxGap;
            inValue.Body.epsilon = epsilon;
            inValue.Body.useHS = useHS;
            return ((Web_Client.FileTransmute.FileHandlerSoap)(this)).RunKarmaLegoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Client.FileTransmute.GetFileResponse Web_Client.FileTransmute.FileHandlerSoap.GetFile(Web_Client.FileTransmute.GetFileRequest request) {
            return base.Channel.GetFile(request);
        }
        
        public byte[] GetFile(string fileName) {
            Web_Client.FileTransmute.GetFileRequest inValue = new Web_Client.FileTransmute.GetFileRequest();
            inValue.Body = new Web_Client.FileTransmute.GetFileRequestBody();
            inValue.Body.fileName = fileName;
            Web_Client.FileTransmute.GetFileResponse retVal = ((Web_Client.FileTransmute.FileHandlerSoap)(this)).GetFile(inValue);
            return retVal.Body.GetFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Client.FileTransmute.GetFileResponse> Web_Client.FileTransmute.FileHandlerSoap.GetFileAsync(Web_Client.FileTransmute.GetFileRequest request) {
            return base.Channel.GetFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Client.FileTransmute.GetFileResponse> GetFileAsync(string fileName) {
            Web_Client.FileTransmute.GetFileRequest inValue = new Web_Client.FileTransmute.GetFileRequest();
            inValue.Body = new Web_Client.FileTransmute.GetFileRequestBody();
            inValue.Body.fileName = fileName;
            return ((Web_Client.FileTransmute.FileHandlerSoap)(this)).GetFileAsync(inValue);
        }
    }
}
